### PR TITLE
Nahum tasks

### PR DESCRIPTION
**Pull request by nahum-smith**
Let me know if you have any questions!

### CODE REVIEW

**Review by pdlug — COMMENTED** [review]
Good initial implementation, a few items:

* Unselecting a journal doesn't work
* Submitting the search form clears the input
* Search appears to be against a re-fetch of articles rather than filtering what is already loaded.

A few minor enhancements to consider:
* Allow the search form to be submitted by hitting enter
* Show a count of how many articles match the search
* Show a nice message if there are no results

**Comment by nahum-smith** [comment]
I changed the Journal Choice design to something I think works much better (left a [TODO:] note there with what I felt needed to be done to finish that task

The remaining suggestions I will finish up this weekend if that if okay

**Comment by nahum-smith** [comment]
The current commit includes:

1. Refactored UserInput layout with more custom components
2. Remove autoclear of input during submit and create clear button instead
3. Completely reworked parsing logic of articles, initial fetch loads ALL articles therefore we have no need to over re-fetch. 
4. Created an articles Object that maps id => array of articles (to avoid looping through arrays for access)
5. Added form around search input so enter keydown will submit search
6. Added both the count and a no results message

**Comment by nahum-smith** [comment]
I continued to work on adding highlighting functionality to the user search term.  While it works, there does seem to be some performance issues now that need to be worked out.

The desired effect would be to click a journal button in the `UserInput` component and set the local state in this component which would change the styling of the button to highlighted.   Then call the `submitUserInput` method to lift the local state up and re-filter articles.  I attempted to do this by calling the `submitUserInput` method in the `setState` callback in the `UserInput` component, but it still looks as though the button does not change styling until the new articles are simultaneously rendered. There was no lag before and now there is, which could be faulty logic in the main App component.  So this does need to be worked out but I think this is a good representation of a potential solution for this feature.

The `Article` component was definitely getting a bit unwieldy so I extracted all components into separate modules and re-organized the directories.  This may not be the best organizational strategy but it suffices for now.

**Pull request closed without merging**
